FROM rust:latest as builder

RUN apt-get update && apt-get install -y musl-tools pkg-config perl make && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
RUN rustup target add x86_64-unknown-linux-musl

ENV SQLX_OFFLINE=true
COPY Cargo.toml ./
RUN mkdir src && echo "fn main() {println!(\"oidjaokdjaj\");}" > /usr/src/app/src/main.rs
RUN cargo build --target x86_64-unknown-linux-musl --release

RUN rm -rf /usr/src/app/target/x86_64-unknown-linux-musl/release/tutors
RUN rm -rf /usr/src/app/src
COPY . .
# RUN ls -la src && sleep 600
RUN cargo build --target x86_64-unknown-linux-musl --release

RUN sh -c "./target/x86_64-unknown-linux-musl/release/tutors" && sleep 600


FROM alpine:latest

WORKDIR /app 

COPY --from=builder /usr/src/app/target/x86_64-unknown-linux-musl/release/tutors /app/tutors
COPY --from=builder /usr/src/app/sql /app/sql
COPY static /app/static 
COPY views /app/views
CMD ["ping", "8.8.8.8"]

