version: "3.9"

services:
  db:
    image: postgres:16.2
    restart: always
#    user: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=kaluga
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
     - ./database:/docker-entrypoint-initdb.d

  website:
    build: ./
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./public:/public

volumes:
  pgdata:
